export const BENEFICIARY_LIST_REQUEST = "BENEFICIARY_LIST_REQUEST";
export const BENEFICIARY_LIST_SUCCESS = "BENEFICIARY_LIST_SUCCESS";
export const BENEFICIARY_LIST_FAIL = "BENEFICIARY_LIST_FAIL";
export const BENEFICIARY_LIST_RESET = "BENEFICIARY_LIST_RESET";
