export const ROLE_REGISTER_REQUEST = "ROLE_REGISTER_REQUEST";
export const ROLE_REGISTER_SUCCESS = "ROLE_REGISTER_SUCCESS";
export const ROLE_REGISTER_FAIL = "ROLE_REGISTER_FAIL";
export const ROLE_REGISTER_RESET = "ROLE_REGISTER_RESET";

export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";
export const ROLE_LIST_RESET = "ROLE_LIST_RESET";

export const ROLE_USER_BY_ID_REQUEST = "ROLE_USER_BY_ID_REQUEST";
export const ROLE_USER_BY_ID_SUCCESS = "ROLE_USER_BY_ID_SUCCESS";
export const ROLE_USER_BY_ID_FAIL = "ROLE_USER_BY_ID_FAIL";
export const ROLE_USER_BY_ID_RESET = "ROLE_USER_BY_ID_RESET";

export const ROLE_UPDATED_REQUEST = "ROLE_UPDATED_REQUEST";
export const ROLE_UPDATED_SUCCESS = "ROLE_UPDATED_SUCCESS";
export const ROLE_UPDATED_FAIL = "ROLE_UPDATED_FAIL";
export const ROLE_UPDATED_RESET = "ROLE_UPDATED_RESET";

export const ROLE_DELETE_REQUEST = "ROLE_DELETE_REQUEST";
export const ROLE_DELETE_SUCCESS = "ROLE_DELETE_SUCCESS";
export const ROLE_DELETE_FAIL = "ROLE_DELETE_FAIL";
export const ROLE_DELETE_RESET = "ROLE_DELETE_RESET";
