export const SAVE_USER = "SAVE_USER";
export const RESET = "RESET";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_PROFILE_PICTURE_REQUEST = "USER_PROFILE_PICTURE_REQUEST";
export const USER_PROFILE_PICTURE_SUCCESS = "USER_PROFILE_PICTURE_SUCCESS";
export const USER_PROFILE_PICTURE_FAIL = "USER_PROFILE_PICTURE_FAIL";
export const USER_PROFILE_PICTURE_RESET = "USER_PROFILE_PICTURE_RESET";
